import marimo

__generated_with = "0.23.16"
app = marimo.App(width="full")


@app.cell
def _():
    import json
    from pathlib import Path

    import marimo as mo
    import numpy as np

    from mbe_rheed_notebook import batch, controls, figures
    from mbe_rheed_sim import SimulationConfig, rheed, run
    from mbe_rheed_sim.kmc import SimulationResult
    from mbe_rheed_sim.paper import FIGURE3_NOMINAL_GA_N_RATIOS

    ROOT = Path(__file__).resolve().parents[1]
    GALLERY_DIR = ROOT / "data" / "gallery"
    GALLERY = json.loads((GALLERY_DIR / "index.json").read_text())
    SAVED_DIR = ROOT / "outputs" / "saved"
    IMAGES = ROOT / "notebooks" / "public"
    return (
        FIGURE3_NOMINAL_GA_N_RATIOS,
        GALLERY,
        GALLERY_DIR,
        IMAGES,
        ROOT,
        SAVED_DIR,
        SimulationConfig,
        SimulationResult,
        batch,
        controls,
        figures,
        json,
        mo,
        np,
        rheed,
        run,
    )


@app.cell
def _(mo):
    mo.md(r"""
    # From surface kinetics to RHEED oscillations: a minimal kinetic Monte Carlo model of MBE

    **Question.** Can a minimal surface-growth model reproduce the characteristic
    layer-by-layer RHEED oscillations reported for GaN growth, and how do growth conditions
    change those oscillations?

    **What this is.** Four events on a solid-on-solid lattice: deposition, diffusion, downward
    hops across a step edge, and desorption. The strained GaN/AlN quantum-dot physics of
    Budagosky and Garcia-Cristobal (2022) is not included, and the RHEED curve is a morphology
    proxy rather than an electron-diffraction calculation, so the comparisons below are
    qualitative.
    """)
    return


@app.cell
def _(IMAGES, mo):
    # Public-domain / CC schematics set the physical scene; every figure after this one is
    # generated by the model. Credits are in the captions.
    _panel = {"background": "#fff", "padding": "8px", "margin": "0 auto"}
    mo.vstack(
        [
            mo.md(r"""
            ## The physical setting

            **Growth.** In molecular-beam epitaxy, effusion cells send directed atomic beams
            onto a heated crystalline substrate under ultra-high vacuum, slowly enough that the
            surface reorganises between arrivals. A RHEED gun grazes that same surface and its
            diffracted intensity is recorded throughout growth, so deposition and the monitoring
            signal come from one experiment.
            """),
            mo.image(
                IMAGES / "01_mbe_chamber_schematic.png",
                alt="MBE chamber: effusion cells, heated substrate, RHEED gun and screen",
                width="100%",
                rounded=True,
                style=_panel | {"max-width": "330px"},
                caption=(
                    "MBE growth chamber with in-situ RHEED monitoring. "
                    '<a href="https://commons.wikimedia.org/wiki/File:MBE.png">Vegar Ottesen, '
                    "Wikimedia Commons, CC BY-SA 3.0</a>."
                ),
            ),
            mo.md(r"""
            **Morphology.** Which morphology results is a kinetic competition: deposition adds
            material, thermally activated diffusion lets it find binding sites, and surface
            energetics and strain set what is favourable. Three canonical outcomes are island
            growth, layer-by-layer growth, and layer-plus-island growth. This model is
            single-species, unstrained homoepitaxy, so it can produce the layer-by-layer and
            rough/mounded regimes but not the strain-driven layer-plus-island case of GaN/AlN
            quantum dots.
            """),
            mo.image(
                IMAGES / "02_thin_film_growth_modes.png",
                alt="Cross-sections of island, layer-by-layer, and layer-plus-island growth",
                width="100%",
                rounded=True,
                style=_panel | {"max-width": "460px"},
                caption=(
                    "Canonical thin-film growth modes at increasing coverage: (a) island, "
                    "(b) layer-by-layer, (c) layer-plus-island. "
                    '<a href="https://commons.wikimedia.org/wiki/File:GrowthModes.png">Acarlso3, '
                    "Wikimedia Commons, public domain</a>."
                ),
            ),
            mo.md(r"""
            **Why RHEED sees it.** At grazing incidence the electron beam samples only the
            topmost layers, so the pattern changes character with the surface itself: streaks
            from a smooth terraced surface, broadened and modulated streaks as step density
            rises, transmission spots once three-dimensional islands stand proud. During
            layer-by-layer growth the specular intensity therefore oscillates once per
            monolayer. **This notebook computes no electron diffraction.** It tracks the
            morphology the diffraction responds to and reports a step-density proxy, defined in
            section 3.
            """),
            mo.image(
                IMAGES / "03_rheed_surface_patterns.png",
                alt="RHEED patterns for smooth, stepped, and 3D-island surfaces",
                width="100%",
                rounded=True,
                style=_panel | {"max-width": "560px"},
                caption=(
                    "Schematic RHEED patterns for smooth, rough/stepped, and 3D-island "
                    "surfaces (generic, not GaN/AlN-specific). "
                    '<a href="https://commons.wikimedia.org/wiki/File:RHEED_patterns_for_'
                    'different_surfaces.png">EWEp, Wikimedia Commons, CC BY-SA 4.0</a>.'
                ),
            ),
        ]
    )
    return


@app.cell
def _(mo):
    mo.vstack(
        [
            mo.md(r"""
            ## 1. A minimal kinetic Monte Carlo model

            The model keeps only the kinetics above: particles land at rate set by the flux,
            explore terraces by thermally activated hops, and become incorporated at island
            edges.

            ### Events

            | Event | Surface change | Competing control |
            |---|---|---|
            | **Deposit** | add one unit at the landing site | flux $F$ |
            | **Diffuse** | move a top unit to a neighboring column | $T$, bonds, barriers |
            | **Attach** | gain lateral neighbors and become less mobile | island geometry |
            | **Desorb** | remove one top unit | $T$, desorption barrier |

            These are the only physical events in this single-species model. The state is an
            integer solid-on-solid height field on a periodic lattice with six neighbors per
            site. A top particle may diffuse laterally or cross one step up or down;
            multi-step hops are forbidden and a downward crossing pays an Ehrlich-Schwoebel
            barrier.

            ### Time stepping and rates

            Residence-time KMC chooses event $i$ with probability $r_i / R$ and advances the
            physical clock by

            $$\Delta t = -\frac{\ln u}{R}, \qquad R=\sum_i r_i,$$

            so deposition, diffusion, and desorption share one clock and a fixed seed gives a
            reproducible trajectory. The rates are

            $$r_{\mathrm{dep}} = F N, \qquad
            r_{\mathrm{diff}} = \nu\exp\left[-\frac{E_{\mathrm{diff}} + nE_b +
            mE_{\mathrm{step}}}{k_B T}\right], \qquad
            r_{\mathrm{des}} = \nu\exp\left[-\frac{E_{\mathrm{des}} + nE_b}{k_B T}\right].$$

            $N$ is the number of sites, $\nu$ an effective attempt frequency,
            $E_{\mathrm{diff}}$ and $E_{\mathrm{des}}$ isolated-particle barriers, $nE_b$ the
            lateral bond contribution, and $m=1$ only for a downward crossing. The energetic
            defaults in the form below are demonstration parameters; the paper source replaces
            them with values fitted to a Ga/N ratio.
            """),
        ]
    )
    return


@app.cell
def _(GALLERY, SAVED_DIR, controls, mo):
    data_source, gallery_choice = controls.source_selector(GALLERY)
    saved_browser = controls.saved_browser(SAVED_DIR)
    preset_choice = controls.preset_selector(GALLERY)
    mo.vstack(
        [
            mo.md(
                "## 2. A layer-by-layer growth experiment\n"
                "Grow a film and watch the surface. Hover any &#9432; for what a control does.\n\n"
                '**Result source** <span data-tooltip="Pre-computed demo loads a stored '
                'trajectory instantly — use this when presenting. Simulate now runs the model '
                'live with the parameters below, single-threaded. Saved run reloads a '
                'trajectory you stored yourself, from the Reproducibility panel at the end." '
                'style="cursor:help">&#9432;</span> picks where the trajectory comes from; '
                '**Start from** <span data-tooltip="Loads the parameters behind a stored demo '
                'into the form, so you can reproduce that scenario and then change one thing '
                'at a time." style="cursor:help">&#9432;</span> loads a stored scenario into '
                "the form."
            ),
            mo.hstack(
                [data_source, gallery_choice, preset_choice],
                justify="start",
                gap=2,
                wrap=True,
            ),
            mo.accordion({"Load a saved run (`.npz`)": saved_browser}),
        ]
    )
    return data_source, gallery_choice, preset_choice, saved_browser


@app.cell
def _(FIGURE3_NOMINAL_GA_N_RATIOS, GALLERY, controls, mo, preset_choice):
    # Rebuilding the form is how a preset moves the sliders: marimo elements take their value
    # at construction, so the cell that owns them re-runs when the preset changes.
    _values = (
        controls.preset_parameters(GALLERY[preset_choice.value])
        if preset_choice.value
        else controls.DEFAULT_PARAMETERS
    )
    get_parameters, _set_parameters = mo.state(_values)
    parameter_form = controls.parameter_form(
        FIGURE3_NOMINAL_GA_N_RATIOS,
        on_change=lambda value: _set_parameters(value or _values),
        values=_values,
    )
    parameter_form
    return (get_parameters,)


@app.cell
def _(mo):
    # A run button lives in its own cell so reading its value does not reset it.
    expensive_override = mo.ui.run_button(label="Run it anyway")
    return (expensive_override,)


@app.cell
def _(
    GALLERY,
    GALLERY_DIR,
    SimulationResult,
    controls,
    data_source,
    expensive_override,
    gallery_choice,
    get_parameters,
    mo,
    saved_browser,
):
    if data_source.value == controls.SAVED_RUN:
        mo.stop(
            not saved_browser.value,
            mo.md("Pick a saved `.npz` file in **Load a saved run** above."),
        )
        _path = saved_browser.path(0)
        simulation = SimulationResult.load_npz(_path)
        growth_rate = None
        experiment_name = _path.stem
        experiment_detail = controls.saved_detail(simulation.config)
        experiment_source = f"saved run `{_path}` — nothing was simulated"
    elif data_source.value == controls.PRE_COMPUTED:
        _entry = gallery_choice.value
        _meta = GALLERY[_entry]
        simulation = SimulationResult.load_npz(GALLERY_DIR / f"{_entry}.npz")
        growth_rate = _meta["predicted_growth_rate_ml_s"]
        experiment_name = _meta["title"]
        experiment_detail = controls.gallery_detail(_meta, simulation.config)
        experiment_source = f"stored trajectory `data/gallery/{_entry}.npz` — nothing was simulated"
    else:
        _config, _estimate, growth_rate, experiment_name, experiment_detail = controls.build_run(
            get_parameters()
        )
        mo.stop(
            controls.is_expensive(_config, _estimate) and not expensive_override.value,
            controls.expensive_warning(_estimate, expensive_override),
        )
        try:
            simulation = controls.run_with_progress(_config, f"Running KMC: {experiment_name}")
        except RuntimeError as _error:
            mo.stop(True, mo.callout(str(_error), kind="danger"))
        experiment_source = (
            f"live run, {_config.lattice_size}x{_config.lattice_size}, seed {_config.seed}"
        )

    coverage_axis = simulation.time_s * growth_rate if growth_rate else simulation.coverage_ml
    coverage_axis_label = (
        "paper-predicted film coverage (ML)" if growth_rate else "film coverage (ML)"
    )
    return (
        coverage_axis,
        coverage_axis_label,
        experiment_detail,
        experiment_name,
        experiment_source,
        simulation,
    )


@app.cell
def _(experiment_detail, experiment_name, experiment_source, mo, simulation):
    mo.md(f"""
    **Active mode:** {experiment_name}

    **Source:** {experiment_source}

    {experiment_detail}

    **Completed:** {simulation.deposited_events} deposition events,
    {simulation.selected_diffusion_events} selected diffusion events
    ({simulation.diffusion_events} nearest-neighbor hop equivalents), and
    {simulation.desorbed_events} desorption events; simulated time
    {simulation.time_s[-1]:.3f} s; final RMS roughness
    {simulation.roughness_ml[-1]:.3f} ML.
    """)
    return


@app.cell
def _(mo, simulation):
    get_frame, set_frame = mo.state(len(simulation.snapshots) - 1, allow_self_loops=True)
    return get_frame, set_frame


@app.cell
def _(mo, set_frame, simulation):
    playback = mo.ui.refresh(
        options=[0.25, 0.5, 1.0],
        label="Playback interval",
        on_change=lambda _value: set_frame(lambda frame: (frame + 1) % len(simulation.snapshots)),
    )
    return (playback,)


@app.cell
def _(mo):
    # Its own cell: the frame-following widgets below are rebuilt on every playback tick, and
    # a rebuilt dropdown would snap back to its constructor value mid-animation.
    display_mode = mo.ui.dropdown(
        options=[
            "3D height surface",
            "Hexagonal cells",
            "Step edges",
            "RHEED beam geometry",
        ],
        value="3D height surface",
        label="Surface view",
    )
    return (display_mode,)


@app.cell
def _(mo, rheed):
    # Also its own cell, for the same reason as the view selector above. The labels carry the
    # phase order because that, not the angle, is what decides whether layers cancel.
    beam_condition = mo.ui.dropdown(
        options={
            f"anti-phase, order {order} ({rheed.antiphase_grazing_angle_deg(order):.2f}°)"
            if order % 2
            else f"in-phase, order {order} ({rheed.antiphase_grazing_angle_deg(order):.2f}°)": (
                rheed.antiphase_grazing_angle_deg(order)
            )
            for order in (1, 2, 3, 4, 5)
        },
        value=f"anti-phase, order {rheed.DEFAULT_PHASE_ORDER} "
        f"({rheed.antiphase_grazing_angle_deg(rheed.DEFAULT_PHASE_ORDER):.2f}°)",
        label="Beam condition",
    )
    return (beam_condition,)


@app.cell
def _(
    beam_condition,
    coverage_axis,
    display_mode,
    get_frame,
    mo,
    np,
    playback,
    set_frame,
    simulation,
):
    _current_frame = min(get_frame(), len(simulation.snapshots) - 1)
    _cycle_labels = {
        0.0: "flat reference",
        0.5: "expected island/step maximum",
        1.0: "expected first-layer completion",
        1.5: "expected renewed roughening",
        2.0: "expected second-layer completion",
    }
    _milestone_indices = {
        (
            f"{coverage:.1f} ML — {_cycle_labels[coverage]}"
            if coverage in _cycle_labels
            else f"{coverage:.1f} ML"
        ): int(np.argmin(np.abs(coverage_axis - coverage)))
        for coverage in np.arange(0.0, max(0.5, float(coverage_axis[-1])) + 0.01, 0.5)
    }
    snapshot_slider = mo.ui.slider(
        0,
        len(simulation.snapshots) - 1,
        value=_current_frame,
        label="Recorded growth frame",
        show_value=True,
        on_change=set_frame,
    )
    milestone_picker = mo.ui.dropdown(
        options=_milestone_indices,
        value=min(
            _milestone_indices,
            key=lambda label: abs(coverage_axis[_current_frame] - float(label.split()[0])),
        ),
        label="Coverage milestone",
        on_change=set_frame,
    )
    mo.vstack(
        [
            mo.md(r"""
            ## 3. From surface morphology to a RHEED proxy

            The signal reported throughout this project is a morphology-based stand-in,

            $$I_{\mathrm{proxy}} = 1 - S_d,$$

            where $S_d$ is the fraction of unique nearest-neighbor bonds whose endpoint heights
            differ. Smooth, nearly complete layers have fewer steps and a larger proxy.

            Below it there is now also an actual diffraction calculation: the **kinematic**
            detector image, $|\sum_j \exp(-i\,\mathbf{q}\cdot\mathbf{R}_j)|^2$ summed over
            the column tops of the same surface. It is single scattering only — real RHEED
            phase and amplitude also depend on refraction, absorption, surface reconstruction,
            and strong multiple scattering, none of which are modelled — but it does produce
            the screen, the streaks, and the specular oscillation from first principles rather
            than by analogy.

            The annotated 0–2 ML milestones encode the **ideal layer-by-layer hypothesis**. The
            linked morphology and proxy show what this stochastic run actually produces;
            disagreement is a result, not hidden by relabeling.
            """),
            mo.hstack(
                [snapshot_slider, milestone_picker, playback, display_mode, beam_condition],
                justify="start",
                gap=2,
                wrap=True,
            ),
        ]
    )
    return


@app.cell
def _(
    beam_condition,
    coverage_axis,
    coverage_axis_label,
    display_mode,
    figures,
    get_frame,
    mo,
    rheed,
    simulation,
):
    _frame = min(get_frame(), len(simulation.snapshots) - 1)
    _heights = simulation.snapshots[_frame]
    _zmax = max(1, int(simulation.snapshots.max()))
    _coverage = float(coverage_axis[_frame])
    screen_pattern = rheed.diffraction_screen(
        _heights, grazing_angle_deg=beam_condition.value
    )
    if display_mode.value == "RHEED beam geometry":
        surface_figure = figures.rheed_geometry(
            _heights, _coverage, _zmax, grazing_angle_deg=beam_condition.value
        )
    else:
        surface_figure = {
            "3D height surface": figures.height_surface,
            "Hexagonal cells": figures.hex_cells,
            "Step edges": figures.step_edges,
        }[display_mode.value](_heights, _coverage, _zmax)
    rheed_figure = figures.rheed_trace(
        coverage_axis,
        simulation.rheed_proxy,
        _frame,
        coverage_axis_label,
        specular=rheed.specular_intensity(
            simulation.snapshots, grazing_angle_deg=beam_condition.value
        ),
    )
    mo.vstack(
        [
            mo.Html("""
                <style>
                @media (max-width: 600px) {
                    div:has(> marimo-plotly) { flex-basis: 100% !important; }
                }
                </style>
            """),
            mo.hstack([surface_figure, rheed_figure], widths="equal", wrap=True, align="center"),
            mo.md(
                "The 3D height view uses array coordinates. **Hexagonal cells** maps the "
                "same periodic axial lattice to Cartesian centers so its six-neighbor "
                "topology is shown without implying a square metric. **Step edges** colours "
                "each site by how many of its six neighbours sit at a different height, "
                "which is the quantity $S_d$ averages. **RHEED beam geometry** puts the "
                "grazing ray, the surface and the lit detector screen in one scene. "
                "On the RHEED trace, "
                "the **green diamond** is the initially flat maximum and the **purple x** "
                "is the most stepped stored frame through the first monolayer."
            ),
        ]
    )
    return (screen_pattern,)


@app.cell
def _(coverage_axis, figures, get_frame, mo, screen_pattern, simulation):
    _frame = min(get_frame(), len(simulation.snapshots) - 1)
    mo.vstack(
        [
            figures.detector_screen(screen_pattern, float(coverage_axis[_frame])),
            mo.md(
                "This is the detector image the surface above would produce, summed over the "
                "same lattice: the vertical **streaks** are the in-plane rods, the bright ring "
                "on the circled **(00) specular beam** is what a RHEED experiment records as "
                "*the* intensity, and everything below 0° is in the substrate's **shadow**. "
                "The horizontal dark bands are exit angles at the *in-phase* condition, where "
                "adjacent terraces scatter together and roughness produces no diffuse "
                "intensity at all.\n\n"
                "Switch the **beam condition** control between odd (anti-phase) and even "
                "(in-phase) orders and watch the dashed specular curve on the right: at "
                "anti-phase the layer cycle cancels and the intensity oscillates, at in-phase "
                "it barely moves. That is the geometric reason RHEED oscillations exist, and "
                "it is why the experimenter chooses the angle. The calculation is kinematic — "
                "single scattering only, no dynamical diffraction, refraction or inelastic "
                "background — so treat the shape over a run as the result, not the absolute "
                "brightness."
            ),
        ]
    )
    return


@app.cell
def _(coverage_axis, coverage_axis_label, figures, mo, simulation):
    observable_figure = figures.observables(
        coverage_axis,
        simulation.roughness_ml,
        simulation.island_density_per_site,
        simulation.rheed_proxy,
        coverage_axis_label,
    )
    mo.vstack(
        [
            observable_figure,
            mo.md(
                "Roughness and island density measure the same surface the proxy is computed "
                "from: the proxy is $1-S_d$ by definition, so it falls whenever nucleation "
                "and island growth create steps and rises again as those islands merge into a "
                "near-complete layer."
            ),
        ]
    )
    return


@app.cell
def _(mo):
    get_artifact_revision, set_artifact_revision = mo.state(0)
    return get_artifact_revision, set_artifact_revision


@app.cell
def _(ROOT, get_artifact_revision, json):
    get_artifact_revision()
    figure3_data = json.loads(
        (ROOT / "data/processed/figure3_simulated_reduced.json").read_text()
    )
    return (figure3_data,)


@app.cell
def _(figure3_data):
    # Every headline claim about the comparison is computed from the artifact, so it cannot
    # drift away from the data the figures below are drawn from.
    _comparisons = figure3_data["comparisons"]
    oscillatory_everywhere = all(
        entry[signal]["is_oscillatory"] for entry in _comparisons for signal in ("reference", "simulation")
    )
    worst_period_gap_ml = max(
        abs(entry["simulation_minus_reference_period_ml"]) for entry in _comparisons
    )
    worst_phase_gap_ml = max(entry["absolute_peak_phase_difference_ml"] for entry in _comparisons)
    reference_damping = [entry["reference"]["damping_rate_per_ml"] for entry in _comparisons]
    simulated_damping = [entry["simulation"]["damping_rate_per_ml"] for entry in _comparisons]
    return (
        oscillatory_everywhere,
        reference_damping,
        simulated_damping,
        worst_period_gap_ml,
        worst_phase_gap_ml,
    )


@app.cell
def _(
    figure3_data,
    figures,
    mo,
    oscillatory_everywhere,
    reference_damping,
    simulated_damping,
    worst_period_gap_ml,
    worst_phase_gap_ml,
):
    figure3_figure, _metric_rows = figures.figure3_comparison(figure3_data)
    _morphology = figure3_data["morphology_sequence"]
    morphology_figure = figures.morphology_sequence(_morphology)
    _provenance = figure3_data["provenance"]
    mo.vstack(
        [
            mo.md("## 4. Partial reproduction of the published RHEED trends"),
            mo.callout(
                mo.md(
                    "**Result.** "
                    + ("Every reference and simulated trace oscillates. " if oscillatory_everywhere else "")
                    + f"Simulated oscillation periods sit within **{worst_period_gap_ml:.2f} ML** "
                    f"of the figure-derived periods and peak phases within "
                    f"**{worst_phase_gap_ml:.2f} ML**, so the model reproduces the *existence* "
                    "and roughly the *period* of layer-by-layer oscillations. It does not "
                    "reproduce their decay: the reference traces damp at "
                    f"{min(reference_damping):.2f} to {max(reference_damping):.2f} per ML while "
                    f"the simulated proxy stays between {min(simulated_damping):+.2f} and "
                    f"{max(simulated_damping):+.2f} per ML. Amplitudes are not comparable at "
                    "all: the author normalization is unavailable and the 7x7 lattice is not "
                    "finite-size converged."
                ),
                kind="info",
            ),
            figure3_figure,
            mo.md(
                "The red curves are **figure-derived experimental RHEED panel coordinates**; "
                "the blue curves are this model's raw morphology-derived `1-S_d` with a "
                "three-seed standard-deviation band. They share time but intentionally use "
                "separate panels and are not the same physical quantity."
            ),
            mo.md(
                "### Quantitative diagnostics\n\n"
                "| Ga/N | period ref/sim (ML) | absolute peak-phase difference (ML) | "
                "damping ref/sim (per ML) | relative amplitude ref/sim |\n"
                "|---:|---:|---:|---:|---:|\n" + _metric_rows + "\n\nRelative amplitude is "
                "referenced to Ga/N = 0.89 separately for each signal. Diagnostics use "
                "paper-predicted coverage = growth rate x time after linear detrending."
            ),
            morphology_figure,
            mo.md(
                f"The morphology sequence is **{_morphology['classification']}**. "
                f"Artifacts were generated by `{_provenance['generated_by']}` at Git commit "
                f"`{_provenance['code_version']['git_commit']}` using lattice "
                f"{_provenance['lattice_size']}x{_provenance['lattice_size']} and seeds "
                f"`{_provenance['seeds']}`. Run `make figure3` to regenerate them."
            ),
        ]
    )
    return


@app.cell
def _(ROOT, get_artifact_revision, json, mo):
    get_artifact_revision()
    sweep_data = json.loads((ROOT / "data/processed/parameter_sweep.json").read_text())
    _temperatures = sweep_data["temperatures_k"]
    _fluxes = sweep_data["fluxes_ml_s"]
    _default = {"temperature_k": _temperatures[1], "flux_ml_s": _fluxes[1]}
    get_sweep_selection, _set_sweep_selection = mo.state(_default)
    sweep_form = (
        mo.md("""
        | Sweep coordinate | Selection |
        |---|---|
        | Temperature | {temperature_k} |
        | Deposition flux | {flux_ml_s} |
    """)
        .batch(
            temperature_k=mo.ui.dropdown(
                {f"{value:.0f} K": value for value in _temperatures},
                value=f"{_default['temperature_k']:.0f} K",
                label="Temperature",
            ),
            flux_ml_s=mo.ui.dropdown(
                {f"{value:.2f} ML/s": value for value in _fluxes},
                value=f"{_default['flux_ml_s']:.2f} ML/s",
                label="Deposition flux",
            ),
        )
        .form(
            submit_button_label="Run selected point",
            bordered=True,
            on_change=lambda value: _set_sweep_selection(value or _default),
        )
    )
    mo.vstack(
        [
            mo.md(
                "## 5. Beyond the paper: a temperature/flux regime map\n"
                "The paper fixes the growth condition. The model does not, so the same machinery "
                "can ask how the oscillation changes with temperature and flux. Select one point "
                "from the reproducible three-seed sweep; the linked run uses seed 0 on the same "
                "16x16 lattice."
            ),
            sweep_form,
        ]
    )
    return get_sweep_selection, sweep_data


@app.cell
def _(SimulationConfig, get_sweep_selection, run):
    sweep_selection = get_sweep_selection()
    selected_sweep_result = run(
        SimulationConfig(
            lattice_size=16,
            target_coverage_ml=2.0,
            temperature_k=float(sweep_selection["temperature_k"]),
            deposition_flux_ml_s=float(sweep_selection["flux_ml_s"]),
            max_isolated_hop_distance=3,
            sample_every_ml=0.05,
            seed=0,
        )
    )
    return selected_sweep_result, sweep_selection


@app.cell
def _(figures, mo, np, selected_sweep_result, sweep_data, sweep_selection):
    sweep_figure = figures.sweep_panels(sweep_data, sweep_selection, selected_sweep_result)
    _row = int(
        np.flatnonzero(np.asarray(sweep_data["temperatures_k"]) == sweep_selection["temperature_k"])[0]
    )
    _column = int(
        np.flatnonzero(np.asarray(sweep_data["fluxes_ml_s"]) == sweep_selection["flux_ml_s"])[0]
    )
    mo.vstack(
        [
            sweep_figure,
            mo.md(
                f"Selected ensemble amplitude: "
                f"**{sweep_data['mean_amplitude'][_row][_column]:.3f} "
                f"+/- {sweep_data['std_amplitude'][_row][_column]:.3f}**; "
                f"single-run final roughness: **{selected_sweep_result.roughness_ml[-1]:.3f} ML**."
            ),
        ]
    )
    return


@app.cell
def _(mo):
    mo.md(r"""
    ## 6. Numerical reliability and model limits

    The seed makes a run exactly reproducible, but one trajectory is not an uncertainty
    estimate. The scripted workflows aggregate fixed seed ensembles instead: `make figure3`
    for the Ga/N comparison and morphology figures, `make sweep` for the temperature/flux
    map, `make convergence` for the generic finite-size check, and `make convergence-figure3`
    for the paper-regime size check.

    **Finite size is the binding limitation.** Detrended proxy amplitude remains strongly
    lattice-size dependent and is not converged through 64x64, so the Figure 3 comparison runs
    at 7x7 as a reduced-scale check and no amplitude claim is made from it. Period and phase are
    far less size-sensitive, which is why they carry the comparison in section 4.

    **Approximations.** Isolated adatoms may hop several sites in one selected event above hop
    limit 1; `make validate-acceleration` measures that 100-seed ensembles stay within a
    quarter standard deviation of exact nearest-neighbor KMC. Strain is outside the model and
    is not needed for this homoepitaxial target. The proxy is morphology, not diffraction; a
    defensible next stage is a kinematic layer-interference model, with full dynamical electron
    scattering outside the baseline.
    """)
    return


@app.cell
def _(
    mo,
    oscillatory_everywhere,
    reference_damping,
    simulated_damping,
    worst_period_gap_ml,
):
    _oscillation_line = (
        "Every paper condition tested oscillates in both the reference and the simulation."
        if oscillatory_everywhere
        else "Not every condition tested produced an oscillation in both signals."
    )
    mo.md(f"""
    ## 7. Conclusions

    1. **A four-event solid-on-solid KMC is enough to produce layer-by-layer oscillations.**
       {_oscillation_line}
    2. **The oscillation is a morphology signal.** The proxy is $1-S_d$, so it is the step
       density that oscillates; the linked morphology view in section 3 shows the islands that
       create those steps forming and merging once per monolayer.
    3. **Growth conditions change the oscillation**, in the paper's Ga/N series and in the
       temperature/flux map of section 5, which the model reaches with the same machinery.
    4. **Agreement with the published data is qualitative, not quantitative.** Periods match
       within {worst_period_gap_ml:.2f} ML, but the experimental traces damp
       ({min(reference_damping):.2f} to {max(reference_damping):.2f} per ML) where the
       simulated proxy does not ({min(simulated_damping):+.2f} to
       {max(simulated_damping):+.2f} per ML).
    5. **Finite size and the proxy definition delimit the claims.** Amplitude is not converged
       through 64x64 and `1-S_d` is not a diffracted intensity, so neither absolute amplitudes
       nor damping should be read as physical predictions of this model.
    """)
    return


@app.cell
def _(mo):
    mo.md("""
    ## Reproducibility and batch workflows

    Everything below regenerates or stores data; no figures live here. One KMC trajectory is
    sequential *in this algorithm* — every event changes the surface the next event is drawn
    from — so a single run cannot be split across cores, and the workers below parallelise
    across *independent* runs instead.
    """)
    return


@app.cell
def _(controls, mo):
    # Own cell: reading a run button resets it.
    save_name, save_button = controls.save_controls()
    mo.hstack([save_name, save_button], justify="start", gap=1, wrap=True)
    return save_button, save_name


@app.cell
def _(SAVED_DIR, controls, mo, save_button, save_name, simulation):
    mo.md(
        controls.save_result(simulation, SAVED_DIR, save_name.value)
        if save_button.value
        else "Saving writes the active result's arrays and configuration to `outputs/saved/`, "
        "which **Result source → Saved run** in section 2 reads back."
    )
    return


@app.cell
def _(batch, mo):
    get_batch_request, set_batch_request = mo.state(None)
    get_batch_process, set_batch_process = mo.state(None, allow_self_loops=True)
    batch_form = batch.controls(
        on_change=lambda value: set_batch_request(dict(value) if value else None)
    )
    mo.vstack(
        [
            mo.md(
                "These controls launch the same reproducible CLI used by `make`. Blank overrides "
                "retain the preset. Successful jobs are retained under `outputs/batches/`, then "
                "atomically promoted to the canonical artifacts; failed or cancelled jobs never "
                "replace canonical data. On promotion, sections 4 and 5 re-read "
                "`data/processed/` and redraw themselves. Only one batch can run per session."
            ),
            mo.accordion(
                {
                    "Canonical seeds, sizes, and measured runtimes": mo.md(
                        "| Workflow | Canonical seeds | Canonical sizes / grid |\n"
                        "|---|---|---|\n"
                        "| Baseline | 2026 | 8x8 |\n"
                        "| GaN Ga/N comparison | 2026-2028 | 7x7, three Ga/N ratios |\n"
                        "| Sweep | 0-2 | 16x16, 3 temperatures x 3 fluxes |\n"
                        "| Generic convergence | 0-2 | 8/16/24 |\n"
                        "| Figure 3 convergence | 0-2 | 8/16/32; add 64 via the size override |\n"
                        "| Acceleration validation | 0-99 | 7x7 exact/accelerated pairs |\n"
                        "| Scientific trends | 0-4 | 8x8, three physics configurations |\n"
                        "| Sweep validation | 0-2 | 24x24, 3 temperatures x 2 fluxes |\n"
                        "| Runtime benchmark | 0 | 64/128/256, sequential |\n\n"
                        "Measured timings: the Ga/N comparison is about 16 s with four workers; "
                        "Figure 3 convergence through 64x64 is about 52 s with three effective "
                        "workers; the sequential 64/128/256 benchmark is about 34 s. Runtime "
                        "varies with the machine and its load."
                    )
                }
            ),
            batch_form,
        ]
    )
    return get_batch_process, get_batch_request, set_batch_process


@app.cell
def _(batch, get_batch_process, get_batch_request, mo, set_batch_process):
    _request = get_batch_request()
    _existing = get_batch_process()
    if _request is None:
        batch_launch_message = mo.md("Select a workflow and press **Launch batch workflow**.")
    elif _existing is not None and _existing["process"].poll() is None:
        batch_launch_message = mo.callout(
            "A batch is already running. Cancel it or wait for it to finish before "
            "launching another.",
            kind="warn",
        )
    elif batch.needs_confirmation(_request) and not _request["confirm_expensive"]:
        batch_launch_message = mo.callout(
            "This workflow is intentionally gated. Tick the expensive-workflow confirmation "
            "and submit again.",
            kind="warn",
        )
    else:
        _state = batch.launch(_request)
        set_batch_process(_state)
        batch_launch_message = mo.callout(
            f"Launched `{_request['workflow']}` as process {_state['process'].pid}.", kind="info"
        )
    batch_launch_message
    return


@app.cell
def _(mo):
    batch_refresh = mo.ui.refresh(
        options=[1.0, 2.0, 5.0], default_interval=1.0, label="Batch status refresh"
    )
    return (batch_refresh,)


@app.cell
def _(batch, batch_refresh, get_batch_process, mo, set_artifact_revision):
    batch_refresh.value
    _state = get_batch_process()
    _status, _elapsed, _just_promoted = batch.read_status(_state)
    if _just_promoted:
        set_artifact_revision(lambda revision: revision + 1)
    cancel_batch = mo.ui.run_button(
        label="Cancel active batch",
        kind="danger",
        disabled=_state is None or _state["process"].poll() is not None,
        on_change=lambda _value: batch.cancel(get_batch_process()),
    )
    mo.vstack(
        [
            mo.md(batch.status_markdown(_status, _elapsed)),
            mo.hstack([batch_refresh, cancel_batch], justify="start", gap=2),
        ]
    )
    return


if __name__ == "__main__":
    app.run()
