import marimo

__generated_with = "0.24.0"
app = marimo.App(width="full")


@app.cell
def _():
    import json
    from pathlib import Path

    import marimo as mo
    import numpy as np

    from mbe_rheed_notebook import controls, figures, reconstruction
    from mbe_rheed_sim import SimulationConfig, rheed, run
    from mbe_rheed_sim.kmc import SimulationResult
    from mbe_rheed_sim.paper import FIGURE3_NOMINAL_GA_N_RATIOS

    ROOT = Path(__file__).resolve().parents[1]
    GALLERY_DIR = ROOT / "data" / "gallery"
    GALLERY = json.loads((GALLERY_DIR / "index.json").read_text())
    SAVED_DIR = ROOT / "outputs" / "saved"
    IMAGES = ROOT / "notebooks" / "public"
    # Committed figures, so the notebook shows them without a rebuild of Git-ignored outputs/.
    ASSETS = ROOT / "assets"
    return (
        ASSETS,
        FIGURE3_NOMINAL_GA_N_RATIOS,
        GALLERY,
        GALLERY_DIR,
        IMAGES,
        ROOT,
        SAVED_DIR,
        SimulationConfig,
        SimulationResult,
        controls,
        figures,
        json,
        mo,
        np,
        reconstruction,
        rheed,
        run,
    )


@app.cell
def _(mo):
    mo.md(r"""
    # From surface kinetics to RHEED oscillations: a minimal kinetic Monte Carlo model of MBE

    **Question.** Can a minimal surface-growth model reproduce the characteristic
    layer-by-layer RHEED oscillations reported for GaN growth, and how do growth conditions
    change those oscillations?

    **What this is.** Four events on a solid-on-solid lattice: deposition, diffusion, downward
    hops across a step edge, and desorption. The strained GaN/AlN quantum-dot physics of
    Budagosky and Garcia-Cristobal (2022) is not included. The headline RHEED curve is a
    morphology proxy, $1-S_d$; a kinematic single-scattering detector screen and specular
    intensity are computed from the same surfaces alongside it. Neither is dynamical RHEED, so
    the comparisons below stay qualitative.
    """)
    return


@app.cell
def _(IMAGES, mo):
    # Public-domain / CC schematics set the physical scene; every figure after this one is
    # generated by the model. Credits are in the captions.
    _panel = {"background": "#fff", "padding": "8px", "margin": "0 auto"}
    mo.vstack(
        [
            mo.md(r"""
            ## The physical setting

            **Growth.** In molecular-beam epitaxy, effusion cells send directed atomic beams
            onto a heated crystalline substrate under ultra-high vacuum, slowly enough that the
            surface reorganises between arrivals. A RHEED gun grazes that same surface and its
            diffracted intensity is recorded throughout growth, so deposition and the monitoring
            signal come from one experiment.
            """),
            mo.image(
                IMAGES / "01_mbe_chamber_schematic.png",
                alt="MBE chamber: effusion cells, heated substrate, RHEED gun and screen",
                width="100%",
                rounded=True,
                style=_panel | {"max-width": "330px"},
                caption=(
                    "MBE growth chamber with in-situ RHEED monitoring. "
                    '<a href="https://commons.wikimedia.org/wiki/File:MBE.png">Vegar Ottesen, '
                    "Wikimedia Commons, CC BY-SA 3.0</a>."
                ),
            ),
            mo.md(r"""
            **Morphology.** Which morphology results is a kinetic competition: deposition adds
            material, thermally activated diffusion lets it find binding sites, and surface
            energetics and strain set what is favourable. Three canonical outcomes are island
            growth, layer-by-layer growth, and layer-plus-island growth. This model is
            single-species, unstrained homoepitaxy, so it can produce the layer-by-layer and
            rough/mounded regimes but not the strain-driven layer-plus-island case of GaN/AlN
            quantum dots.
            """),
            mo.image(
                IMAGES / "02_thin_film_growth_modes.png",
                alt="Cross-sections of island, layer-by-layer, and layer-plus-island growth",
                width="100%",
                rounded=True,
                style=_panel | {"max-width": "460px"},
                caption=(
                    "Canonical thin-film growth modes at increasing coverage: (a) island, "
                    "(b) layer-by-layer, (c) layer-plus-island. "
                    '<a href="https://commons.wikimedia.org/wiki/File:GrowthModes.png">Acarlso3, '
                    "Wikimedia Commons, public domain</a>."
                ),
            ),
            mo.md(r"""
            **Why RHEED sees it.** At grazing incidence the electron beam samples only the
            topmost layers, so the pattern changes character with the surface itself: streaks
            from a smooth terraced surface, broadened and modulated streaks as step density
            rises, transmission spots once three-dimensional islands stand proud. During
            layer-by-layer growth the specular intensity therefore oscillates once per
            monolayer. **The signal plotted throughout is a step-density proxy, not a
            diffraction calculation** - it tracks the morphology the diffraction responds to,
            and is defined in section 3. Section 3 also computes the kinematic diffraction
            screen itself, as a separate observable that is never fed back into the proxy.
            """),
            mo.image(
                IMAGES / "03_rheed_surface_patterns.png",
                alt="RHEED patterns for smooth, stepped, and 3D-island surfaces",
                width="100%",
                rounded=True,
                style=_panel | {"max-width": "560px"},
                caption=(
                    "Schematic RHEED patterns for smooth, rough/stepped, and 3D-island "
                    "surfaces (generic, not GaN/AlN-specific). "
                    '<a href="https://commons.wikimedia.org/wiki/File:RHEED_patterns_for_'
                    'different_surfaces.png">EWEp, Wikimedia Commons, CC BY-SA 4.0</a>.'
                ),
            ),
        ]
    )
    return


@app.cell
def _(mo):
    mo.vstack(
        [
            mo.md(r"""
            ## 1. A minimal kinetic Monte Carlo model

            The model keeps only the kinetics above: particles land at rate set by the flux,
            explore terraces by thermally activated hops, and become incorporated at island
            edges.

            ### Events

            | Event | Surface change | Competing control |
            |---|---|---|
            | **Deposit** | add one unit at the landing site | flux $F$ |
            | **Diffuse** | move a top unit to a neighboring column | $T$, bonds, barriers |
            | **Attach** | gain lateral neighbors and become less mobile | island geometry |
            | **Desorb** | remove one top unit | $T$, desorption barrier |

            These are the only physical events in this single-species model. The state is an
            integer solid-on-solid height field on a periodic lattice with six neighbors per
            site. A top particle may diffuse laterally or cross one step up or down;
            multi-step hops are forbidden and a downward crossing pays an Ehrlich-Schwoebel
            barrier.

            ### Time stepping and rates

            Residence-time KMC chooses event $i$ with probability $r_i / R$ and advances the
            physical clock by

            $$\Delta t = -\frac{\ln u}{R}, \qquad R=\sum_i r_i,$$

            so deposition, diffusion, and desorption share one clock and a fixed seed gives a
            reproducible trajectory. The rates are

            $$r_{\mathrm{dep}} = F N, \qquad
            r_{\mathrm{diff}} = \nu\exp\left[-\frac{E_{\mathrm{diff}} + nE_b +
            mE_{\mathrm{step}}}{k_B T}\right], \qquad
            r_{\mathrm{des}} = \nu\exp\left[-\frac{E_{\mathrm{des}} + nE_b}{k_B T}\right].$$

            $N$ is the number of sites, $\nu$ an effective attempt frequency,
            $E_{\mathrm{diff}}$ and $E_{\mathrm{des}}$ isolated-particle barriers, $nE_b$ the
            lateral bond contribution, and $m=1$ only for a downward crossing. The energetic
            defaults in the form below are demonstration parameters; the paper source replaces
            them with values fitted to a Ga/N ratio.
            """),
        ]
    )
    return


@app.cell
def _(GALLERY, SAVED_DIR, controls, mo):
    data_source, gallery_choice = controls.source_selector(GALLERY)
    saved_browser = controls.saved_browser(SAVED_DIR)
    preset_choice = controls.preset_selector(GALLERY)
    mo.vstack(
        [
            mo.md(
                "## 2. A layer-by-layer growth experiment\n"
                "Grow a film and watch the surface. Hover any &#9432; for what a control does.\n\n"
                "**Result source**"
                + controls.info(
                    "Pre-computed demo loads a stored trajectory instantly - use this when "
                    "presenting. Simulate now runs the model live with the parameters below, "
                    "single-threaded. Saved run reloads a trajectory stored under "
                    "`outputs/saved/`."
                )
                + " picks where the trajectory comes from; **Start from**"
                + controls.info(
                    "Loads the parameters behind a stored demo into the form, so you can "
                    "reproduce that scenario and then change one thing at a time."
                )
                + " loads a stored scenario into the form."
            ),
            mo.hstack(
                [data_source, mo.vstack([gallery_choice, preset_choice], gap=1)],
                justify="start",
                gap=2,
                wrap=True,
            ),
            mo.accordion({"Load a saved run (`.npz`)": saved_browser}),
        ]
    )
    return data_source, gallery_choice, preset_choice, saved_browser


@app.cell
def _(FIGURE3_NOMINAL_GA_N_RATIOS, GALLERY, controls, mo, preset_choice):
    # Rebuilding the form is how a preset moves the sliders: marimo elements take their value
    # at construction, so the cell that owns them re-runs when the preset changes.
    _values = (
        controls.preset_parameters(GALLERY[preset_choice.value])
        if preset_choice.value
        else controls.DEFAULT_PARAMETERS
    )
    get_parameters, _set_parameters = mo.state(_values)
    parameter_form = controls.parameter_form(
        FIGURE3_NOMINAL_GA_N_RATIOS,
        on_change=lambda value: _set_parameters(value or _values),
        values=_values,
    )
    parameter_form
    return (get_parameters,)


@app.cell
def _(mo):
    # A run button lives in its own cell so reading its value does not reset it.
    expensive_override = mo.ui.run_button(label="Run it anyway")
    return (expensive_override,)


@app.cell
def _(
    GALLERY,
    GALLERY_DIR,
    SimulationResult,
    controls,
    data_source,
    expensive_override,
    gallery_choice,
    get_parameters,
    mo,
    saved_browser,
):
    # Only a demo recorded for the regime turns the switch on; see the gallery branch below.
    reconstruction_default = False
    if data_source.value == controls.SAVED_RUN:
        mo.stop(
            not saved_browser.value,
            mo.md("Pick a saved `.npz` file in **Load a saved run** above."),
        )
        _path = saved_browser.path(0)
        simulation = SimulationResult.load_npz(_path)
        growth_rate = None
        experiment_name = _path.stem
        experiment_detail = controls.saved_detail(simulation.config)
        experiment_source = f"saved run `{_path}` - nothing was simulated"
    elif data_source.value == controls.PRE_COMPUTED:
        _entry = gallery_choice.value
        _meta = GALLERY[_entry]
        simulation = SimulationResult.load_npz(GALLERY_DIR / f"{_entry}.npz")
        growth_rate = _meta["predicted_growth_rate_ml_s"]
        experiment_name = _meta["title"]
        experiment_detail = controls.gallery_detail(_meta, simulation.config)
        experiment_source = f"stored trajectory `data/gallery/{_entry}.npz` - nothing was simulated"
        # A demo recorded for the regime arrives with the switch already on, so the view it was
        # built to show is the one that appears.
        reconstruction_default = bool(_meta.get("reconstruction"))
    else:
        _config, _estimate, growth_rate, experiment_name, experiment_detail = controls.build_run(
            get_parameters()
        )
        mo.stop(
            controls.is_expensive(_config, _estimate) and not expensive_override.value,
            controls.expensive_warning(_estimate, expensive_override),
        )
        try:
            simulation = controls.run_with_progress(_config, f"Running KMC: {experiment_name}")
        except RuntimeError as _error:
            mo.stop(True, mo.callout(str(_error), kind="danger"))
        experiment_source = (
            f"live run, {_config.lattice_size}x{_config.lattice_size}, seed {_config.seed}"
        )

    coverage_axis = simulation.time_s * growth_rate if growth_rate else simulation.coverage_ml
    coverage_axis_label = (
        "paper-predicted film coverage (ML)" if growth_rate else "film coverage (ML)"
    )
    return (
        coverage_axis,
        coverage_axis_label,
        experiment_detail,
        experiment_name,
        experiment_source,
        reconstruction_default,
        simulation,
    )


@app.cell
def _(experiment_detail, experiment_name, experiment_source, mo, simulation):
    mo.md(f"""
    **Active mode:** {experiment_name}

    **Source:** {experiment_source}

    {experiment_detail}

    **Completed:** {simulation.deposited_events} deposition events,
    {simulation.selected_diffusion_events} selected diffusion events
    ({simulation.diffusion_events} nearest-neighbor hop equivalents), and
    {simulation.desorbed_events} desorption events; simulated time
    {simulation.time_s[-1]:.3f} s; final RMS roughness
    {simulation.roughness_ml[-1]:.3f} ML.
    """)
    return


@app.cell
def _(mo, reconstruction_default):
    # Its own cell, like the view selector below: a switch rebuilt on a playback tick would snap
    # back to its constructor value. Loading a different run is the one thing that may reposition
    # it, and that is a deliberate act rather than a tick.
    reconstruction_toggle = mo.ui.switch(
        label="Stranski-Krastanov regime", value=reconstruction_default
    )
    return (reconstruction_toggle,)


@app.cell
def _():
    # A plain dict, deliberately. The playback ticker below must not reference the extended run:
    # marimo remounts a rebuilt `mo.ui.refresh` at `off`, so a ticker that named it stopped
    # playing every time the regime switch moved, and the ordered phase was never reached under
    # playback at all. The extension writes what the ticker needs in here instead, and this cell
    # never re-runs, so the ticker is never rebuilt.
    playback_cursor = {"order": None, "total": 1}
    return (playback_cursor,)


@app.cell
def _(
    coverage_axis,
    playback_cursor,
    reconstruction,
    reconstruction_toggle,
    simulation,
):
    # Continues the trajectory past its target coverage with a prescribed ordered phase.
    # `reconstruction.extend` is the identity until the switch above is set, so by default every
    # cell below sees the recorded run exactly as it was simulated. See the module for what the
    # appended frames are and are not.
    display_simulation, display_coverage_axis, reconstruction_order = reconstruction.extend(
        simulation, coverage_axis, enabled=reconstruction_toggle.value
    )
    playback_cursor.update(
        order=reconstruction_order, total=len(display_simulation.snapshots)
    )
    return display_coverage_axis, display_simulation, reconstruction_order


@app.cell
def _(mo, simulation):
    # Deliberately keyed on the recorded run, not on whatever the cell above extended it into:
    # re-running this cell would rebuild the state at its last frame and jump the view there.
    get_frame, set_frame = mo.state(len(simulation.snapshots) - 1, allow_self_loops=True)
    return get_frame, set_frame


@app.cell
def _(mo, playback_cursor, reconstruction, set_frame):
    # marimo renders this as a step button plus an interval dropdown, and the label is plain
    # text beside them. No play triangle here: a glyph in the label is not clickable, and one
    # that looks like a button is worse than a name that reads like a verb.
    playback = mo.ui.refresh(
        options=[0.25, 0.5, 1.0],
        label="**Play the growth**",
        on_change=lambda _value: set_frame(
            lambda frame: reconstruction.next_frame(
                playback_cursor["order"], frame, playback_cursor["total"]
            )
        ),
    )
    return (playback,)


@app.cell
def _(display_simulation, get_frame):
    # Clamped once, here. The frame state outlives the run it was created for, so every cell that
    # reads it needs the same guard, and repeating it is how the four of them drift apart.
    current_frame = min(get_frame(), len(display_simulation.snapshots) - 1)
    return (current_frame,)


@app.cell
def _(mo):
    # Its own cell: the frame-following widgets below are rebuilt on every playback tick, and
    # a rebuilt dropdown would snap back to its constructor value mid-animation.
    display_mode = mo.ui.dropdown(
        options=[
            "3D height surface",
            "Hexagonal cells",
            "Step edges",
            "RHEED beam geometry",
            "Reachable diffraction orders",
        ],
        value="3D height surface",
        label="Surface view",
    )
    return (display_mode,)


@app.cell
def _(mo, rheed):
    # Also its own cell, for the same reason as the view selector above. The labels carry the
    # phase order because that, not the angle, is what decides whether layers cancel.
    beam_condition = mo.ui.dropdown(
        options={
            f"anti-phase, order {order} ({rheed.antiphase_grazing_angle_deg(order):.2f}°)"
            if order % 2
            else f"in-phase, order {order} ({rheed.antiphase_grazing_angle_deg(order):.2f}°)": (
                rheed.antiphase_grazing_angle_deg(order)
            )
            for order in (1, 2, 3, 4, 5)
        },
        value=f"anti-phase, order {rheed.DEFAULT_PHASE_ORDER} "
        f"({rheed.antiphase_grazing_angle_deg(rheed.DEFAULT_PHASE_ORDER):.2f}°)",
        label="Beam condition",
    )
    return (beam_condition,)


@app.cell
def _(mo):
    # Sample azimuth. The triangular surface repeats every 60°, and 0° and 30° are its two
    # mirror directions, so this range covers every distinct pattern once.
    sample_azimuth = mo.ui.slider(
        start=0, stop=60, step=5, value=0, label="Sample azimuth (°)", show_value=True
    )
    return (sample_azimuth,)


@app.cell
def _(
    beam_condition,
    current_frame,
    display_coverage_axis,
    display_mode,
    display_simulation,
    mo,
    np,
    playback,
    reconstruction_toggle,
    sample_azimuth,
    set_frame,
):
    _cycle_labels = {
        0.0: "flat reference",
        0.5: "expected island/step maximum",
        1.0: "expected first-layer completion",
        1.5: "expected renewed roughening",
        2.0: "expected second-layer completion",
    }
    _milestone_indices = {
        (
            f"{coverage:.1f} ML - {_cycle_labels[coverage]}"
            if coverage in _cycle_labels
            else f"{coverage:.1f} ML"
        ): int(np.argmin(np.abs(display_coverage_axis - coverage)))
        for coverage in np.arange(0.0, max(0.5, float(display_coverage_axis[-1])) + 0.01, 0.5)
    }
    snapshot_slider = mo.ui.slider(
        0,
        len(display_simulation.snapshots) - 1,
        value=current_frame,
        label="Recorded growth frame",
        show_value=True,
        on_change=set_frame,
    )
    milestone_picker = mo.ui.dropdown(
        options=_milestone_indices,
        value=min(
            _milestone_indices,
            key=lambda label: abs(
                display_coverage_axis[current_frame] - float(label.split()[0])
            ),
        ),
        label="Coverage milestone",
        on_change=set_frame,
    )
    mo.vstack(
        [
            mo.md(r"""
            ## 3. From surface morphology to a RHEED proxy

            The signal reported throughout this project is a morphology-based stand-in,

            $$I_{\mathrm{proxy}} = 1 - S_d,$$

            where $S_d$ is the fraction of unique nearest-neighbor bonds whose endpoint heights
            differ. Smooth, nearly complete layers have fewer steps and a larger proxy.

            Below it there is now also an actual diffraction calculation: the **kinematic**
            detector image, $|\sum_j \exp(-i\,\mathbf{q}\cdot\mathbf{R}_j)|^2$ summed over
            the column tops of the same surface. It is single scattering only - real RHEED
            phase and amplitude also depend on refraction, absorption, surface reconstruction,
            and strong multiple scattering, none of which are modelled - but it does produce
            the screen, the streaks, and the specular oscillation from first principles rather
            than by analogy.

            The annotated 0–2 ML milestones encode the **ideal layer-by-layer hypothesis**. The
            linked morphology and proxy show what this stochastic run actually produces;
            disagreement is a result, not hidden by relabeling.

            **Do try the Stranski-Krastanov regime.** The switch below carries the run past its
            target coverage into the ordered phase that strained GaN on AlN reaches once its
            wetting layer is complete - the growth mode the primary paper is about, and the one
            thing this model is too simple to reach on its own. The frames past the target are
            therefore prescribed rather than simulated, and everything measured from them is
            measured the ordinary way; the panel under the surface views says exactly which is
            which. It needs a live run of 64x64 or larger to resolve, or the stored 256x256 demo
            in section 2, which arrives with the switch already on. Then press play and watch the
            camera come overhead as the surface orders.
            """),
            # Three rows: which frame is showing, then how it is drawn, then the play control
            # last so it sits directly above the figure it animates.
            mo.hstack(
                [snapshot_slider, milestone_picker],
                justify="start",
                gap=2,
                wrap=True,
            ),
            mo.hstack(
                [display_mode, beam_condition, sample_azimuth, reconstruction_toggle],
                justify="start",
                gap=2,
                wrap=True,
            ),
            mo.hstack([playback], justify="start"),
            mo.md(
                "*Drag **Recorded growth frame** to scrub the run by hand, or animate it with "
                "**Play the growth** just above the figure: the menu is seconds per frame, so "
                "`0.25` runs fast and smooth, `1.0` runs slow and stepped, and `off` pauses. "
                "The circular-arrows button beside the menu advances a single frame each click.*"
            ),
        ]
    )
    return


@app.cell
def _(beam_condition, display_simulation, rheed):
    # Every frame's specular intensity, so the trace below is not recomputing the whole
    # trajectory on every playback tick: it depends on the run and the beam angle, not on which
    # frame is showing. That recompute was most of the tick, and the cells waiting behind it
    # sat dimmed while it ran.
    specular_curve = rheed.specular_intensity(
        display_simulation.snapshots, grazing_angle_deg=beam_condition.value
    )
    return (specular_curve,)


@app.cell
def _(
    beam_condition,
    coverage_axis_label,
    current_frame,
    display_coverage_axis,
    display_mode,
    display_simulation,
    figures,
    mo,
    reconstruction,
    reconstruction_order,
    rheed,
    sample_azimuth,
    simulation,
    specular_curve,
):
    _heights = display_simulation.snapshots[current_frame]
    _coverage = float(display_coverage_axis[current_frame])
    # Camera, colour scale and title for this frame. Without the extension this is just the
    # recorded run's own height range and the builder's default view. The swing has to start from
    # the active mode's own default eye, or switching modes mid-sequence flips the view.
    _default_camera = {
        "RHEED beam geometry": figures.GEOMETRY_CAMERA,
        "Reachable diffraction orders": figures.GEOMETRY_ORDERS_CAMERA,
    }.get(display_mode.value, figures.SURFACE_CAMERA)
    _scene = reconstruction.scene(
        reconstruction_order,
        current_frame,
        display_simulation.snapshots,
        simulation.snapshots,
        _default_camera,
    )
    _zmax = _scene.zmax
    screen_pattern = rheed.diffraction_screen(
        _heights,
        grazing_angle_deg=beam_condition.value,
        azimuth_deg=float(sample_azimuth.value),
    )
    if display_mode.value in ("RHEED beam geometry", "Reachable diffraction orders"):
        # The same pattern the screen figure in the next cell draws, so they cannot disagree.
        surface_figure = figures.rheed_geometry(
            _heights,
            _coverage,
            _zmax,
            grazing_angle_deg=beam_condition.value,
            azimuth_deg=float(sample_azimuth.value),
            pattern=screen_pattern,
            show_orders=display_mode.value == "Reachable diffraction orders",
            camera=_scene.camera,
            revision=_scene.revision,
        )
    elif display_mode.value == "3D height surface":
        surface_figure = figures.height_surface(
            _heights, _coverage, _zmax, camera=_scene.camera, revision=_scene.revision
        )
    else:
        surface_figure = {
            "Hexagonal cells": figures.hex_cells,
            "Step edges": figures.step_edges,
        }[display_mode.value](_heights, _coverage, _zmax)
    if _scene.title:
        # Kept above whatever the mode's own title said rather than replacing it: the geometry
        # views carry the kinematic-scattering disclosure and the disclosed z stretch up there,
        # and a prescribed frame is the last one to drop them.
        surface_figure.update_layout(
            title={
                "automargin": True,
                "text": f"{_scene.title}<br><sub>{surface_figure.layout.title.text}</sub>",
            }
        )
    rheed_figure = figures.rheed_trace(
        display_coverage_axis,
        display_simulation.rheed_proxy,
        current_frame,
        coverage_axis_label,
        specular=specular_curve,
    )
    mo.vstack(
        [
            mo.Html("""
                <style>
                @media (max-width: 600px) {
                    div:has(> marimo-plotly) { flex-basis: 100% !important; }
                }
                </style>
            """),
            mo.hstack([surface_figure, rheed_figure], widths="equal", wrap=True, align="center"),
            # Drawn here, not in a cell of its own: marimo runs cells one at a time, so a cell
            # downstream of `screen_pattern` could not start until this one had finished and sat
            # dimmed for the whole tick - which read as the screen greying out while nothing was
            # being computed. The static prose below still lives in its own cell, which playback
            # never touches.
            figures.detector_screen(screen_pattern, _coverage),
        ]
    )
    return


@app.cell
def _(mo):
    mo.vstack(
        [
            # Sits here rather than in the playback cell above so it does not dim on every tick.
            mo.callout(
                mo.md(
                    "**Why the subtitle can list one rod while three streaks show.** RHEED is "
                    "read off the Ewald construction: because the crystal is finite along the "
                    "surface normal, each 2D reciprocal-lattice point extends into a rod, and an "
                    "order is geometrically accessible exactly when its rod cuts the Ewald "
                    "sphere. At this example condition - 15 keV, 1.65° grazing - only the "
                    "specular $(00)$ rod does, which is all **Ewald-intersecting rods** claims; "
                    "it is not a count of what is bright on the screen. The side intensity is "
                    "real all the same: the simulated surface and its illumination are finite, "
                    "rough and coherence-limited, so reciprocal-space features have finite width "
                    "instead of being delta functions. All of it is kinematic single scattering, "
                    "not full dynamical RHEED.\n\n"
                    '<img src="https://gisaxs.com/images/6/6b/3D_ewald_example.png" '
                    'alt="Ewald sphere cutting a reciprocal lattice, with the scattered rays '
                    'reaching a detector" style="max-width: 340px; width: 100%;">\n\n'
                    "*Textbook Ewald construction - **not** a simulated image, and not output of "
                    "this notebook. Source: [gisaxs.com](https://gisaxs.com/index.php/Ewald_sphere), "
                    "CC BY-SA 3.0.*"
                ),
                kind="info",
            ),
            mo.md(
                "**The surface views.** The 3D height view uses array coordinates. "
                "**Hexagonal cells** maps the same periodic axial lattice to Cartesian "
                "centers so its six-neighbor "
                "topology is shown without implying a square metric. **Step edges** colours "
                "each site by how many of its six neighbours sit at a different height, "
                "which is the quantity $S_d$ averages. **RHEED beam geometry** places the "
                "grazing ray, the surface normal and the detector plane on the same surface "
                "at the beam condition selected above, and paints the computed screen onto "
                "that plane: its centre pixel is exactly where the specular ray lands, so it "
                "is the same data as the 2D screen above. Changing the azimuth rotates the "
                "**sample** in the lab frame while the beam and the plane stay put, so the "
                "morphology is unchanged and the reachable rods move - the specular direction "
                "itself does not, because turning a sample about its own normal cannot move "
                "its mirror direction. Only the grazing angle moves that. "
                "**Reachable diffraction orders** adds one ray per order that `rod_orders()` "
                "finds inside the drawn detector's acceptance, each stopping at its own Ewald "
                "intersection with the plane and labelled with its real $(h,k)$ - so the "
                "azimuth changes which orders exist while $k_i$, $n$ and $k_f^{(00)}$ hold "
                "still. Its z is exaggerated 3x so the rays separate, while the hit positions "
                "stay exact; the two insets are the readable views - a 1:1 side view for the "
                "true grazing angle, and the detector plane face-on with every reachable "
                "$(h,k)$ where it lands. At a shallow condition no first order is reachable at "
                "all, and the figure says so rather than drawing something. "
                "On the RHEED trace, "
                "the **green diamond** is the initially flat maximum and the **purple x** "
                "is the most stepped stored frame through the first monolayer."
            ),
            mo.md(
                "**The detector screen.** This is the detector image the surface above would "
                "produce, built from the "
                "exact Ewald construction: each `(h k)` reciprocal rod is intersected with "
                "the sphere $|\\mathbf{k}_f| = |\\mathbf{k}_i|$, and the crosses mark where "
                "that intersection lands. **Only orders the geometry actually reaches are "
                "drawn.** A rod exists only when $|\\mathbf{G}_{hk}| \\le k\\sin\\theta_i$, "
                "so at the shallowest beam conditions the specular $(00)$ beam is the only "
                "order on the screen and the side orders appear - *below* the specular "
                "beam, on the zeroth Laue circle - once the grazing angle is raised past "
                "about 2.1° at 15 keV. Turning the **sample azimuth** rotates the whole "
                "reciprocal lattice against the fixed beam, sweeping the Ewald sphere across "
                "the rods: away from a mirror direction they climb the Laue circle and leave "
                "this screen's ±3° acceptance, which is why the order count in the subtitle "
                "changes. Everything below 0° is in the substrate's **shadow**.\n\n"
                "**Three separate widths, not one.** The rod width in reciprocal space is set "
                "by the **coherence length** of the illumination, a real-space Gaussian whose "
                "transform is $4\\sqrt{2}\\ln 2 / L$ wide; beam **divergence** acts on the "
                "incident direction and is integrated over there; a detector **point spread** "
                "blurs the finished image. They are applied in three different domains "
                "because they are three different pieces of physics. The simulation box is "
                "tiled or cropped to fill the illuminated patch, so a 7×7 run and a 64×64 run "
                "of the same physical surface give the same streaks.\n\n"
                "**Two limits.** The model surface repeats every $N$ sites, so disorder "
                "can only scatter into multiples of $2\\pi/Na$; once the coherence length "
                "approaches the box width that background breaks into discrete satellites, "
                "and translating the illuminated patch cannot cure it because the satellite "
                "positions are fixed by the box period, not by where the beam lands. And the "
                "calculation is kinematic - single scattering, no dynamical diffraction, "
                "refraction, absorption, Kikuchi lines or inelastic background - so absolute "
                "brightness means nothing. The shape over a run is the result.\n\n"
                "Switch the **beam condition** control between odd (anti-phase) and even "
                "(in-phase) orders and watch the dashed specular curve on the right: at "
                "anti-phase the layer cycle cancels and the intensity oscillates, at in-phase "
                "it barely moves. That is the geometric reason RHEED oscillations exist, and "
                "it is why the experimenter chooses the angle."
            ),
        ]
    )
    return


@app.cell
def _(
    coverage_axis_label,
    current_frame,
    display_coverage_axis,
    figures,
    mo,
    reconstruction,
    reconstruction_order,
    reconstruction_toggle,
    simulation,
):
    # Say why nothing happened rather than leaving a switch that appears to do nothing: the stored
    # demos are too small a lattice to resolve the template, so this needs a live run.
    mo.stop(
        reconstruction_order is None,
        mo.md(
            f"**Stranski-Krastanov regime:** needs at least "
            f"{reconstruction.MIN_LATTICE_SIZE} sites to resolve; this run is "
            f"{simulation.config.lattice_size}x{simulation.config.lattice_size}."
        )
        if reconstruction_toggle.value
        else mo.md(""),
    )
    # Stop at the transition. Past it the coverage is deliberately frozen while the ordering
    # keeps moving, so plotting the rest against coverage draws every later frame on top of the
    # same few tenths of a monolayer: a scribble, not a curve.
    _emergence = reconstruction_order.transition_frame + 1
    mo.vstack(
        [
            figures.reconstruction_order_parameter(
                display_coverage_axis[:_emergence],
                reconstruction_order.r_sk[:_emergence],
                min(current_frame, _emergence - 1),
                reconstruction_order.theta_ml,
                reconstruction.CRITICAL_ORDER_PARAMETER,
                coverage_axis_label,
            ),
            mo.md(
                "**Not a simulation result.** Every frame at or below the run's target coverage "
                "is unmodified KMC output. The frames beyond it are a *prescribed* ordered phase "
                "appended by `mbe_rheed_notebook.reconstruction`: this model has no strain and no "
                "reconstruction, so it cannot produce one, and the overlay only shows what the "
                "Stranski-Krastanov transition of the primary paper would look like in these same "
                "observables. What is genuinely computed is everything measured *from* those "
                "surfaces: the coverage, roughness, island density, and $1-S_d$ proxy come from "
                "the ordinary `mbe_rheed_sim.observables` functions, and "
                r"$R_{SK} = \langle H, H_t\rangle / (\|H\|\,\|H_t\|)$ is the cosine "
                "similarity between each mean-subtracted surface and the fully ordered template, "
                "so the quoted \u0398 is an interpolated crossing rather than a chosen number."
            ),
        ]
    )
    return


@app.cell
def _(
    coverage_axis_label,
    display_coverage_axis,
    display_simulation,
    figures,
    mo,
):
    observable_figure = figures.observables(
        display_coverage_axis,
        display_simulation.roughness_ml,
        display_simulation.island_density_per_site,
        display_simulation.rheed_proxy,
        coverage_axis_label,
    )
    mo.vstack(
        [
            observable_figure,
            mo.md(
                "Roughness and island density measure the same surface the proxy is computed "
                "from: the proxy is $1-S_d$ by definition, so it falls whenever nucleation "
                "and island growth create steps and rises again as those islands merge into a "
                "near-complete layer."
            ),
        ]
    )
    return


@app.cell
def _(ROOT, json):
    figure3_data = json.loads(
        (ROOT / "data/processed/figure3_simulated_reduced.json").read_text()
    )
    return (figure3_data,)


@app.cell
def _(figure3_data):
    # Every headline claim about the comparison is computed from the artifact, so it cannot
    # drift away from the data the figures below are drawn from.
    _comparisons = figure3_data["comparisons"]
    oscillatory_everywhere = all(
        entry[signal]["is_oscillatory"] for entry in _comparisons for signal in ("reference", "simulation")
    )
    worst_period_gap_ml = max(
        abs(entry["simulation_minus_reference_period_ml"]) for entry in _comparisons
    )
    worst_phase_gap_ml = max(entry["absolute_peak_phase_difference_ml"] for entry in _comparisons)
    reference_damping = [entry["reference"]["damping_rate_per_ml"] for entry in _comparisons]
    simulated_damping = [entry["simulation"]["damping_rate_per_ml"] for entry in _comparisons]
    return (
        oscillatory_everywhere,
        reference_damping,
        simulated_damping,
        worst_period_gap_ml,
        worst_phase_gap_ml,
    )


@app.cell
def _(
    ASSETS,
    figure3_data,
    figures,
    mo,
    oscillatory_everywhere,
    reference_damping,
    simulated_damping,
    worst_period_gap_ml,
    worst_phase_gap_ml,
):
    figure3_figure, _metric_rows = figures.figure3_comparison(figure3_data)
    _morphology = figure3_data["morphology_sequence"]
    _provenance = figure3_data["provenance"]
    mo.vstack(
        [
            mo.md("## 4. Partial reproduction of the published RHEED trends"),
            mo.callout(
                mo.md(
                    "**Result.** "
                    + ("Every reference and simulated trace oscillates. " if oscillatory_everywhere else "")
                    + f"Simulated oscillation periods sit within **{worst_period_gap_ml:.2f} ML** "
                    f"of the figure-derived periods and peak phases within "
                    f"**{worst_phase_gap_ml:.2f} ML**, so the model reproduces the *existence* "
                    "and roughly the *period* of layer-by-layer oscillations. It does not "
                    "reproduce their decay: the reference traces damp at "
                    f"{min(reference_damping):.2f} to {max(reference_damping):.2f} per ML while "
                    f"the simulated proxy stays between {min(simulated_damping):+.2f} and "
                    f"{max(simulated_damping):+.2f} per ML. Amplitudes are not comparable at "
                    "all: the author normalization is unavailable and the 7x7 lattice is not "
                    "finite-size converged."
                ),
                kind="info",
            ),
            figure3_figure,
            mo.md(
                "The red curves are **figure-derived experimental RHEED panel coordinates**; "
                "the blue curves are this model's raw morphology-derived `1-S_d` with a "
                "three-seed standard-deviation band. They share time but intentionally use "
                "separate panels and are not the same physical quantity."
            ),
            mo.md(
                "### Quantitative diagnostics\n\n"
                "| Ga/N | period ref/sim (ML) | absolute peak-phase difference (ML) | "
                "damping ref/sim (per ML) | relative amplitude ref/sim |\n"
                "|---:|---:|---:|---:|---:|\n" + _metric_rows + "\n\nRelative amplitude is "
                "referenced to Ga/N = 0.89 separately for each signal. Diagnostics use "
                "paper-predicted coverage = growth rate x time after linear detrending."
            ),
            # A 128x128 surface is 16k sites per panel. Drawn as interactive markers that is
            # tens of thousands of SVG nodes per figure and the page stops responding, so the
            # morphology views are the committed PNGs `make figure3` already writes.
            mo.image(
                ASSETS / "figure4_inspired_morphology.png",
                alt="Homoepitaxial surface height maps from 0 to 2 ML at Ga/N = 0.82",
                width="100%",
                rounded=True,
            ),
            mo.md(
                f"The morphology sequence is **{_morphology['classification']}**. "
                f"Artifacts were generated by `{_provenance['generated_by']}` at Git commit "
                f"`{_provenance['code_version']['git_commit']}` using lattice "
                f"{_provenance['lattice_size']}x{_provenance['lattice_size']} and seeds "
                f"`{_provenance['seeds']}`. Run `make figure3` to regenerate them."
            ),
        ]
    )
    return


@app.cell
def _(ASSETS, figure3_data, mo):
    _montage = figure3_data["morphology_montage"]
    mo.vstack(
        [
            mo.md("### Top-down morphology comparison across Figure 3 conditions"),
            mo.md(
                "The trace above says *when* the proxy is high or low; this says *what the "
                "surface looks like* at those two points. Rows are coverage, columns are the "
                "paper's three Ga/N ratios, all from the same ensemble the comparison above "
                "uses, so no extra simulation is involved.\n\n"
                "At **0.50 ML** a layer is half filled, so the surface carries the most island "
                "edge and `1-S_d` sits at its minimum. At **1.00 ML** that layer has closed "
                "and the surface smooths back out, which is the half of the cycle that puts "
                "the oscillation there at all. Across the columns, the paper-derived Ga/N "
                "conditions change the effective Ga flux and so how far the surface gets "
                "from ideal layer-by-layer filling.\n\n"
                "Colour is column height. The step-edge view of the same surface - each site "
                "coloured by how many of its six neighbours sit at a different height, which "
                "is the quantity `S_d` averages - is available live in section 2 for any "
                "surface you run there."
            ),
            mo.image(
                ASSETS / "figure3_morphology_montage.png",
                alt=(
                    "Top-down height maps at 0.5 and 1.0 ML for Ga/N = 0.68, 0.82 and 0.89"
                ),
                width="100%",
                rounded=True,
            ),
            mo.md(
                f"This montage is **{_montage['classification']}**. Coverage is the "
                f"{_montage['coordinate']}."
            ),
        ]
    )
    return


@app.cell
def _(ROOT, json, mo):
    sweep_data = json.loads((ROOT / "data/processed/parameter_sweep.json").read_text())
    _oscillatory_fraction = sweep_data["oscillatory_fraction"]
    _seed_count = len(sweep_data["seeds"])
    _total_runs = sum(len(row) for row in _oscillatory_fraction) * _seed_count
    _oscillatory_runs = round(sum(sum(row) for row in _oscillatory_fraction) * _seed_count)
    _temperatures = sweep_data["temperatures_k"]
    _fluxes = sweep_data["fluxes_ml_s"]
    _default = {"temperature_k": _temperatures[1], "flux_ml_s": _fluxes[1]}
    get_sweep_selection, _set_sweep_selection = mo.state(_default)
    sweep_form = (
        mo.md("""
        | Sweep coordinate | Selection |
        |---|---|
        | Temperature | {temperature_k} |
        | Deposition flux | {flux_ml_s} |
    """)
        .batch(
            temperature_k=mo.ui.dropdown(
                {f"{value:.0f} K": value for value in _temperatures},
                value=f"{_default['temperature_k']:.0f} K",
                label="Temperature",
            ),
            flux_ml_s=mo.ui.dropdown(
                {f"{value:.2f} ML/s": value for value in _fluxes},
                value=f"{_default['flux_ml_s']:.2f} ML/s",
                label="Deposition flux",
            ),
        )
        .form(
            submit_button_label="Run selected point",
            bordered=True,
            on_change=lambda value: _set_sweep_selection(value or _default),
        )
    )
    mo.vstack(
        [
            mo.md(
                "## 5. Beyond the paper: how temperature and flux affect surface roughening\n"
                "A small exploratory sweep, not a second result. The paper fixes the growth "
                "condition; the model does not, so the same machinery can ask how the *surface* "
                "responds to temperature and flux. The map below is final RMS roughness, a "
                "morphology observable that stays meaningful even where the proxy trace is a "
                "monotonic decay rather than an oscillation. Across this sweep, "
                f"**{_oscillatory_runs}/{_total_runs} runs are classified as oscillatory**, so "
                "nothing here should be read as a RHEED-oscillation regime map. Select "
                "one point from the reproducible six-seed sweep; the linked run uses seed 0 on a "
                "16x16 lattice."
            ),
            sweep_form,
        ]
    )
    return get_sweep_selection, sweep_data


@app.cell
def _(SimulationConfig, get_sweep_selection, run):
    sweep_selection = get_sweep_selection()
    selected_sweep_result = run(
        SimulationConfig(
            lattice_size=16,
            target_coverage_ml=2.0,
            temperature_k=float(sweep_selection["temperature_k"]),
            deposition_flux_ml_s=float(sweep_selection["flux_ml_s"]),
            max_isolated_hop_distance=3,
            sample_every_ml=0.05,
            seed=0,
        )
    )
    return selected_sweep_result, sweep_selection


@app.cell
def _(figures, mo, np, selected_sweep_result, sweep_data, sweep_selection):
    sweep_figure = figures.sweep_panels(sweep_data, sweep_selection, selected_sweep_result)
    _row = int(
        np.flatnonzero(np.asarray(sweep_data["temperatures_k"]) == sweep_selection["temperature_k"])[0]
    )
    _column = int(
        np.flatnonzero(np.asarray(sweep_data["fluxes_ml_s"]) == sweep_selection["flux_ml_s"])[0]
    )
    _seeds = len(sweep_data["seeds"])
    mo.vstack(
        [
            sweep_figure,
            mo.md(
                f"Selected ensemble final roughness: "
                f"**{sweep_data['mean_final_roughness_ml'][_row][_column]:.3f} "
                f"+/- {sweep_data['std_final_roughness_ml'][_row][_column]:.3f} ML** "
                f"(seed 0 single run: **{selected_sweep_result.roughness_ml[-1]:.3f} ML**). "
                f"Detrended proxy amplitude here is "
                f"**{sweep_data['mean_detrended_amplitude'][_row][_column]:.3f} "
                f"+/- {sweep_data['std_detrended_amplitude'][_row][_column]:.3f}**, which is a "
                f"range about the linear trend, not evidence of an oscillation: "
                f"**{round(sweep_data['oscillatory_fraction'][_row][_column] * _seeds):d}"
                f"/{_seeds} seeds** at this point are classified as oscillatory."
            ),
        ]
    )
    return


@app.cell
def _(mo):
    mo.md(r"""
    ## 6. Numerical reliability and model limits

    The seed makes a run exactly reproducible, but one trajectory is not an uncertainty
    estimate. The scripted workflows aggregate fixed seed ensembles instead: `make figure3`
    for the Ga/N comparison and morphology figures, `make sweep` for the temperature/flux
    map, `make convergence` for the generic finite-size check, and `make convergence-figure3`
    for the paper-regime size check.

    **Finite size is the binding limitation.** Detrended proxy amplitude remains strongly
    lattice-size dependent and is not converged through 64x64, so the Figure 3 comparison runs
    at 7x7 as a reduced-scale check and no amplitude claim is made from it. Period and phase are
    far less size-sensitive, which is why they carry the comparison in section 4.

    **Approximations.** Isolated adatoms may hop several sites in one selected event above hop
    limit 1; `make validate-acceleration` measures that 100-seed ensembles stay within a
    quarter standard deviation of exact nearest-neighbor KMC. Strain is outside the model and
    is not needed for this homoepitaxial target. The proxy is morphology, not diffraction; a
    defensible next stage is a kinematic layer-interference model, with full dynamical electron
    scattering outside the baseline.
    """)
    return


@app.cell
def _(
    mo,
    oscillatory_everywhere,
    reference_damping,
    simulated_damping,
    worst_period_gap_ml,
):
    _oscillation_line = (
        "Every paper condition tested oscillates in both the reference and the simulation."
        if oscillatory_everywhere
        else "Not every condition tested produced an oscillation in both signals."
    )
    mo.md(f"""
    ## 7. Conclusions

    1. **A four-event solid-on-solid KMC is enough to produce layer-by-layer oscillations.**
       {_oscillation_line}
    2. **The oscillation is a morphology signal.** The proxy is $1-S_d$, so it is the step
       density that oscillates; the linked morphology view in section 3 shows the islands that
       create those steps forming and merging once per monolayer.
    3. **Growth conditions change the surface.** The paper's Ga/N series changes the
       oscillation; the exploratory temperature/flux sweep in section 5 changes final
       roughness without producing oscillations at all, and is reported as such.
    4. **Agreement with the published data is qualitative, not quantitative.** Periods match
       within {worst_period_gap_ml:.2f} ML, but the experimental traces damp
       ({min(reference_damping):.2f} to {max(reference_damping):.2f} per ML) where the
       simulated proxy does not ({min(simulated_damping):+.2f} to
       {max(simulated_damping):+.2f} per ML).
    5. **Finite size and the proxy definition delimit the claims.** Amplitude is not converged
       through 64x64 and `1-S_d` is not a diffracted intensity, so neither absolute amplitudes
       nor damping should be read as physical predictions of this model.
    """)
    return


if __name__ == "__main__":
    app.run()
